name: 💡 Event Proposal
description: Propose a new event (workshop, talk, hackathon, etc.) for the HiredX Full-stack Club.
title: "[REDIRECT] Event Proposal - Please use the Events Repo"
labels: ["event-proposal-redirect", "meta"] # Add a label to easily identify these
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ➡️ Please submit your Event Proposal in the dedicated `events` repository.

        Thank you for wanting to propose an event! For proper tracking, discussion, and planning, all event proposals for the HiredX Full-stack Club are managed directly within our central `events` repository.

        ---

        ### **Click the link below to go to the correct form:**

        **[Propose a New Event in the Events Repository](https://github.com/HiredX-Fullstack-Club/events/issues/new?template=event-proposal.yml)**

        ---

        This issue (in the current repository) will be automatically closed by our team. Please proceed with creating your proposal using the link above.